import { auth } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";

import prismadb from "@/lib/prismadb";
import { checkSubscription } from "@/lib/subscription";
import { reserveApiLimit, rollbackApiLimit } from "@/lib/api-limit";
import { classifyPromptIntent, generateConversation, generateCode, GeminiMessage } from "@/lib/gemini";
import { generateImageWithFallback, generateMusicWithFallback, generateVideo } from "@/lib/media";
import { matchIdentityQuery, sanitizeOutput, maskModelName } from "@/lib/identity-guard";

export async function POST(req: Request) {
  let reservedCredit = false;
  let targetUserId: string | null = null;

  try {
    const { userId } = await auth();
    const body = await req.json();
    const { prompt, conversationId, userTimeZone } = body;

    if (!userId) {
      return new NextResponse("Unauthorized", { status: 401 });
    }

    targetUserId = userId;

    if (!prompt || typeof prompt !== "string" || !prompt.trim()) {
      return new NextResponse("Prompt is required", { status: 400 });
    }

    const isPro = await checkSubscription();

    // Atomically reserve a free trial credit up front within a DB transaction.
    // This strictly eliminates check-then-act race conditions across concurrent requests.
    if (!isPro) {
      const hasCredit = await reserveApiLimit(userId);
      if (!hasCredit) {
        return new NextResponse("Free trial has expired. Please upgrade to pro.", {
          status: 403,
        });
      }
      reservedCredit = true;
    }

    // Step 1: Manage Conversation Session (Find or Create)
    let currentConversation = null;
    if (conversationId) {
      currentConversation = await prismadb.conversation.findUnique({
        where: { id: conversationId, userId },
      });
    }

    if (!currentConversation) {
      // Derive a clean 4-6 word title from the user prompt
      const words = prompt.trim().split(/\s+/).slice(0, 6).join(" ");
      const title = words.length > 40 ? `${words.slice(0, 40)}...` : words;

      currentConversation = await prismadb.conversation.create({
        data: {
          ...(conversationId ? { id: conversationId } : {}),
          userId,
          title: title || "New Chat",
        },
      });
    }

    // Fetch recent conversation history before saving the new user message (sliding window of last 10 messages)
    const pastMessages = await prismadb.message.findMany({
      where: { conversationId: currentConversation.id },
      orderBy: { createdAt: "desc" },
      take: 10,
      select: {
        role: true,
        content: true,
        type: true,
      },
    });

    const conversationHistory: GeminiMessage[] = pastMessages.reverse().map((msg) => ({
      role: msg.role as "user" | "assistant",
      content: msg.content,
      type: msg.type,
    }));

    // Save User Message to Database
    await prismadb.message.create({
      data: {
        conversationId: currentConversation.id,
        role: "user",
        content: prompt,
        type: "text",
      },
    });

    // Step 2: Deterministic Identity & Confidentiality Guard (Layer 1 Interceptor)
    // Intercepts identity, creator, ownership, and backend queries with 0 latency and 100% leak protection
    const identityMatch = matchIdentityQuery(prompt);
    if (identityMatch) {
      const isInitialChat = pastMessages.length <= 1;
      if (isInitialChat) {
        await prismadb.conversation.update({
          where: { id: currentConversation.id },
          data: { title: identityMatch.title },
        });
      }

      const maskedEngine = maskModelName("CONVERSATION");
      const assistantMsg = await prismadb.message.create({
        data: {
          conversationId: currentConversation.id,
          role: "assistant",
          content: identityMatch.response,
          type: "text",
          modelUsed: maskedEngine,
        },
      });

      return NextResponse.json({
        id: assistantMsg.id,
        role: "assistant",
        type: "text",
        content: identityMatch.response,
        modelUsed: maskedEngine,
        conversationTitle: identityMatch.title,
        createdAt: assistantMsg.createdAt,
      });
    }

    // Step 3: Classify Prompt Intent via Gemini Fallback Router with Context Memory
    console.log(`[Omnimodal Chat] Classifying prompt: "${prompt.slice(0, 60)}..."`);
    const classification = await classifyPromptIntent(prompt, conversationHistory);
    console.log(`[Omnimodal Chat] Intent detected: ${classification.category}`);

    // Update conversation title with the smart, concise title generated by Gemini
    if (classification.title) {
      const isInitialChat = pastMessages.length <= 1;
      const hasGenericTitle =
        currentConversation.title === "New Chat" ||
        currentConversation.title === "New Conversation" ||
        currentConversation.title.endsWith("...") ||
        /^(compose|create|make|generate|write|draw|paint|hey|just)\b/i.test(currentConversation.title);

      if (isInitialChat || hasGenericTitle) {
        currentConversation = await prismadb.conversation.update({
          where: { id: currentConversation.id },
          data: { title: classification.title },
        });
      }
    }

    let responseData: {
      type: "text" | "code" | "image" | "audio" | "video";
      content: string;
      mediaUrl?: string | string[];
      modelUsed?: string;
      duration?: number;
    };

    // Step 4: Dispatch to the corresponding specialized model
    switch (classification.category) {
      case "IMAGE": {
        const imageResult = await generateImageWithFallback(classification.extractedPrompt);
        responseData = {
          type: "image",
          content: classification.extractedPrompt,
          mediaUrl: imageResult.url,
          modelUsed: maskModelName("IMAGE", imageResult.modelUsed),
        };
        break;
      }

      case "MUSIC": {
        const musicResult = await generateMusicWithFallback(
          classification.extractedPrompt,
          classification.duration
        );
        responseData = {
          type: "audio",
          content: classification.extractedPrompt,
          mediaUrl: musicResult.url,
          modelUsed: maskModelName("MUSIC", musicResult.modelUsed),
          duration: musicResult.duration,
        };
        break;
      }

      case "VIDEO": {
        const videoResult = await generateVideo(classification.extractedPrompt);
        responseData = {
          type: "video",
          content: classification.extractedPrompt,
          mediaUrl: videoResult.url,
          modelUsed: maskModelName("VIDEO", videoResult.modelUsed),
          duration: videoResult.duration,
        };
        break;
      }

      case "CODE": {
        const codeResult = await generateCode(prompt, conversationHistory, userTimeZone);
        responseData = {
          type: "code",
          content: sanitizeOutput(codeResult.text, prompt),
          modelUsed: maskModelName("CODE", codeResult.modelUsed),
        };
        break;
      }

      case "CONVERSATION":
      default: {
        const convResult = await generateConversation(prompt, conversationHistory, userTimeZone);
        responseData = {
          type: "text",
          content: sanitizeOutput(convResult.text, prompt),
          modelUsed: maskModelName("CONVERSATION", convResult.modelUsed),
        };
        break;
      }
    }

    // Save Assistant Message to Database
    const mediaUrlString = Array.isArray(responseData.mediaUrl)
      ? responseData.mediaUrl[0]
      : responseData.mediaUrl || null;

    await prismadb.message.create({
      data: {
        conversationId: currentConversation.id,
        role: "assistant",
        content: responseData.content || "",
        type: responseData.type,
        mediaUrl: mediaUrlString,
        modelUsed: responseData.modelUsed || null,
        duration: responseData.duration || null,
      },
    });

    // Note: conversation.updatedAt is managed automatically by Prisma's @updatedAt
    // directive — no explicit update needed here.

    return NextResponse.json({
      conversationId: currentConversation.id,
      title: currentConversation.title,
      ...responseData,
    });
  } catch (error: any) {
    // If generation threw an error before completing, rollback the atomically reserved credit
    if (reservedCredit && targetUserId) {
      await rollbackApiLimit(targetUserId);
    }
    console.error("[OMNIMODAL_CHAT_ERROR]", error);
    return new NextResponse(error?.message || "Internal Server Error", { status: 500 });
  }
}
