"use client";

import { useState, useRef } from "react";
import Image from "next/image";
import TypewriterComponent from "typewriter-effect";
import Link from "next/link";
import { useAuth } from "@clerk/nextjs";
import { 
  ArrowRight, 
  Sparkles, 
  Zap, 
  MessageSquare, 
  Code2, 
  ImageIcon, 
  Music, 
  Video, 
  Check, 
  Copy, 
  Play, 
  Pause,
  SlidersHorizontal,
  ExternalLink
} from "lucide-react";

import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

type DemoTab = "chat" | "code" | "image" | "music" | "video";

export const LandingHero = () => {
  const { isSignedIn } = useAuth();
  const [activeTab, setActiveTab] = useState<DemoTab>("chat");
  const [isPlayingAudio, setIsPlayingAudio] = useState(false);
  const [copiedCode, setCopiedCode] = useState(false);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  const toggleAudio = () => {
    if (!audioRef.current) return;
    if (isPlayingAudio) {
      audioRef.current.pause();
      setIsPlayingAudio(false);
    } else {
      audioRef.current
        .play()
        .then(() => setIsPlayingAudio(true))
        .catch(() => setIsPlayingAudio(false));
    }
  };

  const demoItems = {
    chat: {
      title: "Smart Conversation",
      prompt: "How does Genius.ai combine 5 AI modalities into one workspace?",
      response:
        "Genius.ai uses an omnimodal engine. Instead of forcing you to switch tabs between ChatGPT, Midjourney, and Suno, you can converse, generate clean code, synthesize studio images, and compose audio from one unified interface with persistent history.",
      badge: "Gemini 2.5 Flash",
      color: "from-violet-500 to-indigo-600",
      textColor: "text-violet-500",
      borderColor: "border-violet-500/30",
      icon: MessageSquare,
    },
    code: {
      title: "Full-Stack Code Synthesis",
      prompt: "Write a React hook to handle dark mode with localStorage persistence",
      codeSnippet: `// useDarkMode.ts - Generated by Genius.ai
import { useState, useEffect } from 'react';

export function useDarkMode() {
  const [theme, setTheme] = useState<'dark' | 'light'>(() => {
    return (localStorage.getItem('theme') as 'dark' | 'light') || 'dark';
  });

  useEffect(() => {
    document.documentElement.classList.toggle('dark', theme === 'dark');
    localStorage.setItem('theme', theme);
  }, [theme]);

  return { theme, toggleTheme: () => setTheme(t => t === 'dark' ? 'light' : 'dark') };
}`,
      badge: "TypeScript & Next.js",
      color: "from-emerald-500 to-teal-600",
      textColor: "text-emerald-500",
      borderColor: "border-emerald-500/30",
      icon: Code2,
    },
    image: {
      title: "Hyper-Detailed Visual Art",
      prompt: "A stunning cinematic hyper-realistic portrait of a cybernetic tiger with glowing circuits walking through a neon-lit rainy Tokyo cyberpunk alley, 8k digital art",
      badge: "Flux Ghibsky Model",
      color: "from-pink-500 to-rose-600",
      textColor: "text-pink-500",
      borderColor: "border-pink-500/30",
      icon: ImageIcon,
    },
    music: {
      title: "Studio Audio & Soundtracks",
      prompt: "Lo-fi ambient chord progression with warm electric piano, vinyl crackle, and soft harmonic atmosphere",
      badge: "Riffusion Engine",
      color: "from-amber-500 to-orange-600",
      textColor: "text-amber-500",
      borderColor: "border-amber-500/30",
      icon: Music,
    },
    video: {
      title: "Cinematic AI Video",
      prompt: "A breathtaking cinematic 8k drone shot of northern lights aurora borealis glowing emerald green over snow-covered fjord mountains at dusk",
      badge: "Zeroscope XL",
      color: "from-blue-500 to-cyan-600",
      textColor: "text-blue-500",
      borderColor: "border-blue-500/30",
      icon: Video,
    },
  };

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2000);
  };

  return (
    <section className="relative pt-24 sm:pt-28 pb-24 md:pt-32 md:pb-32 overflow-hidden">
      {/* Aurora Ambient Glow Effects */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[450px] aurora-glow-1 pointer-events-none blur-3xl opacity-70" />
      <div className="absolute top-1/3 right-10 w-[500px] h-[350px] aurora-glow-2 pointer-events-none blur-3xl opacity-50 hidden md:block" />

      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Announcement Badge */}
        <div className="flex justify-center mb-6">
          <div className="inline-flex items-center gap-x-2 px-3.5 py-1.5 rounded-full glass-pill text-xs font-semibold text-foreground/90 shadow-sm hover:scale-105 transition-transform cursor-default">
            <span className="flex h-2 w-2 rounded-full bg-violet-500 animate-ping" />
            <Sparkles className="w-3.5 h-3.5 text-violet-500" />
            <span>Genius.ai 2.0 is Live: Next-Gen Omnimodal Studio</span>
          </div>
        </div>

        {/* Main Hero Headline */}
        <div className="text-center max-w-4xl mx-auto space-y-4">
          <h1 className="text-3xl sm:text-5xl md:text-6xl lg:text-7xl font-extrabold tracking-tight text-foreground leading-[1.15]">
            The All-in-One AI Studio for
            <span className="block mt-2 text-gradient min-h-[1.25em] whitespace-nowrap overflow-hidden">
              <TypewriterComponent
                options={{
                  strings: [
                    "Smart Conversations.",
                    "Code Generation.",
                    "Image Creation.",
                    "Studio Music.",
                    "Cinematic Video.",
                  ],
                  autoStart: true,
                  loop: true,
                  deleteSpeed: 25,
                  delay: 50,
                }}
              />
            </span>
          </h1>

          <p className="text-base sm:text-xl text-muted-foreground max-w-2xl mx-auto font-normal leading-relaxed pt-2">
            Why pay for 5 separate AI subscriptions? Genius.ai brings deep reasoning, code generation, studio visuals, audio, and video under <strong>one unified roof</strong> with persistent conversation history.
          </p>

          {/* Primary Action CTAs */}
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-6 pb-3">
            <Link href={isSignedIn ? "/dashboard" : "/sign-up"} className="w-full sm:w-auto">
              <Button
                size="lg"
                className="w-full sm:w-auto px-8 py-6 rounded-full text-base font-semibold bg-gradient-to-r from-violet-600 via-purple-600 to-pink-600 hover:from-violet-700 hover:to-pink-700 text-white shadow-xl shadow-purple-500/25 border-0 hover:scale-105 active:scale-95 transition-all group"
              >
                <Zap className="w-5 h-5 mr-2 fill-white group-hover:scale-110 transition-transform" />
                Start Creating For Free
                <ArrowRight className="w-4 h-4 ml-2 group-hover:translate-x-1 transition-transform" />
              </Button>
            </Link>

            <a href="#preview" className="w-full sm:w-auto">
              <Button
                variant="outline"
                size="lg"
                className="w-full sm:w-auto px-7 py-6 rounded-full text-base font-semibold glass-pill hover:bg-black/5 dark:hover:bg-white/10 transition-all hover:scale-105"
              >
                <SlidersHorizontal className="w-4 h-4 mr-2 text-muted-foreground" />
                Explore Interactive Demo
              </Button>
            </a>
          </div>

          {/* Trust Badges */}
          <div className="flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-xs text-muted-foreground pt-3">
            <span className="flex items-center gap-x-1.5">
              <Check className="w-3.5 h-3.5 text-emerald-500" /> 5 Free Credits on Sign Up
            </span>
            <span className="flex items-center gap-x-1.5">
              <Check className="w-3.5 h-3.5 text-emerald-500" /> No Credit Card Required
            </span>
            <span className="flex items-center gap-x-1.5">
              <Check className="w-3.5 h-3.5 text-emerald-500" /> Saved Conversation History
            </span>
          </div>
        </div>

        {/* Interactive Live Preview Sandbox */}
        <div id="preview" className="mt-16 md:mt-24">
          <div className="text-center mb-6">
            <h2 className="text-xl md:text-2xl font-bold tracking-tight text-foreground">
              Experience the Omnimodal Engine
            </h2>
            <p className="text-sm text-muted-foreground">
              Click through the modalities below to test how Genius.ai generates different media seamlessly:
            </p>
          </div>

          {/* Modality Selector Pills */}
          <div className="flex items-center justify-center flex-wrap gap-2 mb-6">
            {(
              [
                { id: "chat", label: "Conversation", icon: MessageSquare },
                { id: "code", label: "Code", icon: Code2 },
                { id: "image", label: "Image Art", icon: ImageIcon },
                { id: "music", label: "Audio Music", icon: Music },
                { id: "video", label: "Video Render", icon: Video },
              ] as const
            ).map((tab) => {
              const Icon = tab.icon;
              const isActive = activeTab === tab.id;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={cn(
                    "flex items-center gap-x-2 px-4 py-2 rounded-full text-xs sm:text-sm font-semibold transition-all duration-200",
                    isActive
                      ? "bg-foreground text-background shadow-md scale-105"
                      : "glass-pill text-muted-foreground hover:text-foreground hover:scale-102"
                  )}
                >
                  <Icon className="w-4 h-4" />
                  {tab.label}
                </button>
              );
            })}
          </div>

          {/* Sandbox Interactive Card Window */}
          <div className="glass-card rounded-2xl overflow-hidden border border-black/10 dark:border-white/10 shadow-2xl transition-all max-w-4xl mx-auto">
            {/* Window Title Bar */}
            <div className="px-5 py-3.5 bg-muted/40 border-b border-black/5 dark:border-white/10 flex items-center justify-between">
              <div className="flex items-center gap-x-2">
                <div className="w-3 h-3 rounded-full bg-rose-500/80" />
                <div className="w-3 h-3 rounded-full bg-amber-500/80" />
                <div className="w-3 h-3 rounded-full bg-emerald-500/80" />
                <span className="text-xs font-mono text-muted-foreground ml-2 hidden sm:inline">
                  genius.ai / studio / {activeTab}
                </span>
              </div>
              <div className="flex items-center gap-x-2">
                <span className="text-xs font-semibold px-2 py-0.5 rounded-full bg-primary/10 text-primary border border-primary/20">
                  {demoItems[activeTab].badge}
                </span>
              </div>
            </div>

            {/* Prompt Row */}
            <div className="p-4 sm:p-6 border-b border-black/5 dark:border-white/10 bg-background/50">
              <div className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1.5 flex items-center gap-x-1.5">
                <Sparkles className="w-3.5 h-3.5 text-primary" /> User Prompt:
              </div>
              <p className="text-sm sm:text-base font-medium text-foreground bg-muted/40 p-3 rounded-xl border border-black/5 dark:border-white/5">
                &ldquo;{demoItems[activeTab].prompt}&rdquo;
              </p>
            </div>

            {/* Response Showcase */}
            <div className="p-5 sm:p-7 min-h-[260px] flex items-center justify-center">
              {/* CHAT TAB */}
              {activeTab === "chat" && (
                <div className="w-full space-y-4 animate-in fade-in duration-300">
                  <div className="flex items-start gap-x-3">
                    <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-violet-600 to-indigo-600 flex items-center justify-center text-white shrink-0 shadow-md">
                      <Sparkles className="w-4 h-4" />
                    </div>
                    <div className="space-y-3 flex-1 text-sm text-foreground/90 leading-relaxed bg-muted/30 p-4 rounded-xl border border-black/5 dark:border-white/5">
                      <p>{demoItems.chat.response}</p>
                      <div className="flex items-center gap-2 pt-1">
                        <span className="text-[11px] px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 font-medium">
                          ✓ Persistent thread saved
                        </span>
                        <span className="text-[11px] px-2 py-0.5 rounded bg-violet-500/10 text-violet-600 dark:text-violet-400 font-medium">
                          ✓ Multi-turn context active
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {/* CODE TAB */}
              {activeTab === "code" && (
                <div className="w-full animate-in fade-in duration-300">
                  <div className="relative rounded-xl overflow-hidden bg-slate-50 dark:bg-slate-950 text-slate-800 dark:text-slate-100 font-mono text-xs sm:text-sm p-4 border border-slate-200 dark:border-white/10 shadow-sm dark:shadow-inner transition-colors duration-300">
                    <div className="flex items-center justify-between pb-3 mb-3 border-b border-slate-200 dark:border-white/10">
                      <div className="flex items-center gap-x-2">
                        <div className="flex items-center gap-1.5">
                          <span className="w-2.5 h-2.5 rounded-full bg-rose-500/80" />
                          <span className="w-2.5 h-2.5 rounded-full bg-amber-500/80" />
                          <span className="w-2.5 h-2.5 rounded-full bg-emerald-500/80" />
                        </div>
                        <span className="text-xs text-slate-500 dark:text-slate-400 font-medium ml-1">useDarkMode.ts</span>
                      </div>
                      <button
                        onClick={() => handleCopy(demoItems.code.codeSnippet)}
                        className="flex items-center gap-x-1.5 text-xs text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white px-2.5 py-1 rounded-md bg-slate-200/60 dark:bg-white/5 hover:bg-slate-200 dark:hover:bg-white/10 border border-slate-300/60 dark:border-white/10 transition"
                      >
                        {copiedCode ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                        {copiedCode ? "Copied" : "Copy Code"}
                      </button>
                    </div>
                    <pre className="overflow-x-auto leading-relaxed text-xs sm:text-sm font-mono">
                      <code>
                        <span className="text-slate-400 dark:text-slate-500 italic">{"// useDarkMode.ts – Generated by Genius.ai"}</span>{"\n"}
                        <span className="text-purple-600 dark:text-purple-400 font-semibold">import</span> {"{ "}
                        <span className="text-blue-600 dark:text-blue-400">useState</span>,{" "}
                        <span className="text-blue-600 dark:text-blue-400">useEffect</span>
                        {" } "}
                        <span className="text-purple-600 dark:text-purple-400 font-semibold">from</span>{" "}
                        <span className="text-emerald-600 dark:text-emerald-400">&apos;react&apos;</span>;{"\n\n"}
                        <span className="text-purple-600 dark:text-purple-400 font-semibold">export function</span>{" "}
                        <span className="text-blue-600 dark:text-blue-400 font-medium">useDarkMode</span>() {"{\n"}
                        {"  "}<span className="text-purple-600 dark:text-purple-400 font-semibold">const</span> [theme, setTheme] ={" "}
                        <span className="text-blue-600 dark:text-blue-400">useState</span>
                        &lt;<span className="text-emerald-600 dark:text-emerald-400">&apos;dark&apos;</span> |{" "}
                        <span className="text-emerald-600 dark:text-emerald-400">&apos;light&apos;</span>&gt;(() =&gt; {"{\n"}
                        {"    "}<span className="text-purple-600 dark:text-purple-400 font-semibold">return</span> (localStorage.
                        <span className="text-blue-600 dark:text-blue-400">getItem</span>
                        (<span className="text-emerald-600 dark:text-emerald-400">&apos;theme&apos;</span>) <span className="text-purple-600 dark:text-purple-400 font-semibold">as</span>{" "}
                        <span className="text-emerald-600 dark:text-emerald-400">&apos;dark&apos;</span> |{" "}
                        <span className="text-emerald-600 dark:text-emerald-400">&apos;light&apos;</span>) ||{" "}
                        <span className="text-emerald-600 dark:text-emerald-400">&apos;dark&apos;</span>;{"\n"}
                        {"  "});{"\n\n"}
                        {"  "}<span className="text-blue-600 dark:text-blue-400">useEffect</span>(() =&gt; {"{\n"}
                        {"    "}document.documentElement.classList.<span className="text-blue-600 dark:text-blue-400">toggle</span>
                        (<span className="text-emerald-600 dark:text-emerald-400">&apos;dark&apos;</span>, theme ==={" "}
                        <span className="text-emerald-600 dark:text-emerald-400">&apos;dark&apos;</span>);{"\n"}
                        {"    "}localStorage.<span className="text-blue-600 dark:text-blue-400">setItem</span>
                        (<span className="text-emerald-600 dark:text-emerald-400">&apos;theme&apos;</span>, theme);{"\n"}
                        {"  }, [theme]);\n\n"}
                        {"  "}<span className="text-purple-600 dark:text-purple-400 font-semibold">return</span>{" { theme, toggleTheme: () => setTheme(t => t === "}
                        <span className="text-emerald-600 dark:text-emerald-400">&apos;dark&apos;</span> ?{" "}
                        <span className="text-emerald-600 dark:text-emerald-400">&apos;light&apos;</span> :{" "}
                        <span className="text-emerald-600 dark:text-emerald-400">&apos;dark&apos;</span>){" };\n"}
                        {"}\n"}
                      </code>
                    </pre>
                  </div>
                </div>
              )}

              {/* IMAGE TAB */}
              {activeTab === "image" && (
                <div className="w-full flex flex-col md:flex-row items-center gap-6 animate-in fade-in duration-300">
                  <div className="relative w-full md:w-1/2 aspect-square rounded-xl overflow-hidden shadow-2xl border border-black/10 dark:border-white/10 group bg-slate-950">
                    <Image
                      src="/demo-image.jpg"
                      alt="AI Generated Cybernetic Tiger"
                      fill
                      className="object-cover group-hover:scale-105 transition-transform duration-700"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-black/20 opacity-80 group-hover:opacity-50 transition-opacity" />
                    <div className="absolute top-3 right-3 z-10">
                      <a
                        href="/demo-image.jpg"
                        download="genius-ai-cyber-tiger.jpg"
                        className="px-2.5 py-1.5 rounded-lg bg-black/60 hover:bg-black/80 backdrop-blur-md text-white border border-white/20 inline-flex items-center gap-1.5 text-xs font-medium transition shadow-lg"
                        title="Download Real AI Generation"
                      >
                        <ArrowRight className="w-3 h-3 rotate-90" />
                        <span>Save PNG</span>
                      </a>
                    </div>
                    <div className="absolute bottom-3 left-3 right-3 z-10 space-y-1">
                      <p className="text-xs font-bold text-white drop-shadow">Flux Cybernetic Tiger</p>
                      <div className="flex items-center gap-2">
                        <span className="text-[10px] px-2 py-0.5 rounded-full bg-pink-500/80 backdrop-blur-md text-white font-mono">
                          1024 x 1024
                        </span>
                        <span className="text-[10px] text-white/90">Photorealistic • 8k Resolution</span>
                      </div>
                    </div>
                  </div>
                  <div className="w-full md:w-1/2 space-y-3">
                    <div className="inline-flex items-center gap-1.5 text-xs font-semibold text-pink-500 bg-pink-500/10 px-2.5 py-0.5 rounded-full border border-pink-500/20">
                      <Sparkles className="w-3 h-3" /> Live Generation Output
                    </div>
                    <h3 className="text-lg font-bold text-foreground">Flux High-Resolution Art Engine</h3>
                    <p className="text-sm text-muted-foreground leading-relaxed">
                      Powered by the Flux Ghibsky illustration model. Synthesizes intricate textures, realistic reflections, and volumetric lighting from single-sentence prompts.
                    </p>
                    <div className="flex items-center gap-2 pt-2">
                      <Link href={isSignedIn ? "/dashboard" : "/sign-up"}>
                        <Button size="sm" className="rounded-full bg-gradient-to-r from-pink-600 to-rose-600 text-white text-xs">
                          Generate Your Own Art
                          <ArrowRight className="w-3.5 h-3.5 ml-1.5" />
                        </Button>
                      </Link>
                    </div>
                  </div>
                </div>
              )}

              {/* MUSIC TAB */}
              {activeTab === "music" && (
                <div className="w-full space-y-5 animate-in fade-in duration-300">
                  <audio
                    ref={audioRef}
                    src="/demo-audio.mp3"
                    onEnded={() => setIsPlayingAudio(false)}
                  />
                  <div className="p-6 rounded-2xl bg-gradient-to-r from-amber-500/15 via-orange-500/10 to-amber-500/5 border border-amber-500/20 flex flex-col sm:flex-row items-center justify-between gap-5 shadow-lg">
                    <div className="flex items-center gap-x-4 w-full sm:w-auto">
                      <button
                        onClick={toggleAudio}
                        className="w-14 h-14 rounded-full bg-gradient-to-r from-amber-500 to-orange-600 flex items-center justify-center text-white shadow-xl shadow-amber-500/30 hover:scale-110 active:scale-95 transition-all"
                        aria-label="Toggle Audio Demo"
                      >
                        {isPlayingAudio ? <Pause className="w-6 h-6 fill-white" /> : <Play className="w-6 h-6 ml-0.5 fill-white" />}
                      </button>
                      <div>
                        <p className="text-base font-bold text-foreground">Lo-Fi Sunset Resonance</p>
                        <p className="text-xs text-muted-foreground flex items-center gap-1.5 mt-0.5">
                          <span className={cn("w-2 h-2 rounded-full", isPlayingAudio ? "bg-amber-500 animate-ping" : "bg-muted-foreground")} />
                          {isPlayingAudio ? "Playing original AI synthesis..." : "Click play to listen to real audio"}
                        </p>
                      </div>
                    </div>

                    {/* Animated Waveform Visualizer */}
                    <div className="flex items-end gap-1.5 h-10 w-full sm:w-56 justify-center bg-black/10 dark:bg-white/5 p-2 rounded-xl">
                      {[35, 70, 95, 50, 80, 100, 40, 85, 65, 45, 90, 75, 30, 85, 95, 60, 40, 80].map((height, i) => (
                        <div
                          key={i}
                          style={{ height: isPlayingAudio ? `${Math.max(18, (height * (i % 2 === 0 ? 1.15 : 0.85)) % 100)}%` : `${height * 0.35}%` }}
                          className={cn(
                            "w-1.5 rounded-full transition-all duration-150",
                            isPlayingAudio ? "bg-amber-500 animate-pulse" : "bg-muted-foreground/30"
                          )}
                        />
                      ))}
                    </div>
                  </div>
                  <p className="text-xs text-center text-muted-foreground">
                    Real AI audio synthesized via Riffusion spectrogram modeling. Royalty-free for streams, podcasts, games, and video soundtracks.
                  </p>
                </div>
              )}

              {/* VIDEO TAB */}
              {activeTab === "video" && (
                <div className="w-full flex flex-col md:flex-row items-center gap-6 animate-in fade-in duration-300">
                  <div className="relative w-full md:w-1/2 aspect-video rounded-xl overflow-hidden shadow-2xl border border-black/10 dark:border-white/10 group bg-black">
                    <video
                      src="/demo-video.mp4"
                      autoPlay
                      loop
                      muted
                      playsInline
                      className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
                    />
                    <div className="absolute top-3 right-3 z-10">
                      <span className="text-[10px] font-mono font-semibold px-2 py-1 rounded-md bg-black/60 backdrop-blur-md text-white border border-white/20">
                        Zeroscope 1080p
                      </span>
                    </div>
                    <div className="absolute bottom-3 left-3 z-10">
                      <span className="text-xs font-semibold px-2.5 py-1 rounded-full bg-emerald-500/80 backdrop-blur-md text-white flex items-center gap-1.5 shadow">
                        <span className="w-2 h-2 rounded-full bg-white animate-pulse" />
                        AI Video Motion
                      </span>
                    </div>
                  </div>
                  <div className="w-full md:w-1/2 space-y-3">
                    <div className="inline-flex items-center gap-1.5 text-xs font-semibold text-blue-500 bg-blue-500/10 px-2.5 py-0.5 rounded-full border border-blue-500/20">
                      <Sparkles className="w-3 h-3" /> Real Video Output
                    </div>
                    <h3 className="text-lg font-bold text-foreground">Smooth Cinematic Video Synthesis</h3>
                    <p className="text-sm text-muted-foreground leading-relaxed">
                      Powered by Zeroscope XL. Generates continuous cinematic camera motions, aerial landscapes, and atmospheric B-roll directly from prompts.
                    </p>
                    <div className="flex items-center gap-2 pt-2">
                      <Link href={isSignedIn ? "/dashboard" : "/sign-up"}>
                        <Button size="sm" className="rounded-full bg-gradient-to-r from-blue-600 to-cyan-600 text-white text-xs">
                          Render Your Video
                          <ArrowRight className="w-3.5 h-3.5 ml-1.5" />
                        </Button>
                      </Link>
                    </div>
                  </div>
                </div>
              )}
            </div>

            {/* Bottom Footer of Sandbox Card */}
            <div className="px-6 py-4 bg-muted/20 border-t border-black/5 dark:border-white/10 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-muted-foreground">
              <span className="flex items-center gap-x-1.5">
                <span className="w-2 h-2 rounded-full bg-emerald-500" /> All 5 modalities run in one seamless studio
              </span>
              <Link href={isSignedIn ? "/dashboard" : "/sign-up"} className="font-semibold text-primary hover:underline flex items-center gap-1">
                Open Studio Free <ExternalLink className="w-3 h-3" />
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
